// <auto-generated />
namespace BGames.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mapeando_Plataforma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mapeando_Plataforma));
        
        string IMigrationMetadata.Id
        {
            get { return "201807280402180_Mapeando_Plataforma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
